### PR TITLE
[Backport 2.2.x][FIXES #413] REST login createSession overrides both obtained access_token and expiring

### LINKED ISSUE #413: REST login createSession overrides both obtained access_token and expiring
1. The filter after a login does not stop the filter chain in order to hit the `geostore` filter and create an "inMemorySession" here too
2. `geostore` hits the `RESTSessionServiceImpl.login()` method which only check for an authenticated user on the `SecurityContext`, rewrites the current `Session` by setting a default expiring time, and returns the new one without the `access_token`

```java
@Override
    public SessionToken login(SecurityContext sc) throws ParseException {
        Calendar expires = new GregorianCalendar();
        expires.add(Calendar.SECOND, (int) getSessionTimeout());
        User user = extractAuthUser(sc);
        if (user != null) {

            UserSession session = null;
            if (user instanceof User) {
                session = new UserSessionImpl(null, user, expires);
                session.setExpirationInterval(getSessionTimeout());
            }
            return toSessionToken(userSessionService.registerNewSession(session), session);
        }
        return null;
    }
```

What we need to do is to update the geostore contract and make the `registerNewSession` method return a `UserSession` instead of a simple `String`

`public UserSession registerNewSession(UserSession session);`

### PR DESCRIPTION
**Pull request by afabiani**

### CODE REVIEW

File: src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTSessionServiceImpl.java [hunk 1]
```diff
@@ -174,22 +171,27 @@ public SessionToken login(SecurityContext sc) throws ParseException {
...
+                        : sessionToken.getExpirationInterval());
         token.setTokenType(BEARER_TYPE);
         return token;
     }
 
     @Override
     public SessionToken refresh(SecurityContext sc, String sessionId, String refreshToken) {
         String provider =
-                (String) RequestContextHolder.getRequestAttributes().getAttribute(PROVIDER_KEY, 0);
+                (String)
```
Comment (tdipisa) [inline src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTSessionServiceImpl.java:192]: @afabiani why did you include also this further change in respect to the PR on master branch: https://github.com/geosolutions-it/geostore/pull/414/files

Comment (afabiani) [reply src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTSessionServiceImpl.java:192]: This does not change anything in term of logic. It's just a reinforcement that the object shouldn't be null.

Comment (tdipisa) [reply src/modules/rest/impl/src/main/java/it/geosolutions/geostore/services/rest/impl/RESTSessionServiceImpl.java:192]: I know, but in theory we should keep separated (with separated PRs) things  not directly involved in a backport to avoid confusion. I saw the same is already on master at least so, that's ok.

**Review by tdipisa — APPROVED** [review]
